import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Layout/Navbar";
import Footer from "./Layout/Footer";
import { CartProvider } from "./components/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Welcome! | Stripe E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.className}`}>
        <CartProvider>
          <>
            <Navbar />
            <div className="min-h-[calc(100vh-10rem)] md:min-h-[calc(100vh-12rem)] mx-auto max-5xl font-sans">
              {children}
            </div>
            <Footer />
          </>
        </CartProvider>
      </body>
    </html>
  );
}
